package reference;

public enum GameEvent {
	PLAYER_JOINED_GAME,
	GAME_RUNNABLE,
	GAME_STARTED,
	BOMB_OWNER_CHANGED,
	PLAYER_RECEIVED_QUESTION,
	BOMB_OWNER_ANSWER_RIGHT,
	BOMB_OWNER_ANSWER_WRONG,
	BOMB_EXPLODED
}
